In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress
import sqlite3


In [2]:
# create connection to database

con = sqlite3.connect("db/movies.db")
sql = f"""
   SELECT * FROM movie_data
   """

# bring in db to pandas dataframe
movies = pd.read_sql(sql, con)
movies.head()

color    director_name  num_critic_for_reviews  duration  \
0  Color    James Cameron                   723.0     178.0   
1  Color  Stephen Sommers                   106.0     106.0   
2  Color  Terrence Malick                   222.0     150.0   
3  Color    Brian Robbins                    76.0      98.0   
4  Color      Brad Peyton                   178.0      94.0   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    208.0                   855.0     Jason Flemyng   
2                      0.0                   855.0  Michael Greyeyes   
3                     48.0                   722.0  Joel David Moore   
4                     62.0                   722.0    Dwayne Johnson   

   actor_1_facebook_likes        gross  \
0                  1000.0  760505847.0   
1                  3000.0   11146409.0   
2                 23000.0   12712093.0   
3                 21000.0   61112916.0   
4                 14000.0  103812241.0   

                                          genres  ...  \
0                Action|Adventure|Fantasy|Sci-Fi  ...   
1                 Action|Adventure|Horror|Sci-Fi  ...   
2                Biography|Drama|History|Romance  ...   
3                          Comedy|Family|Fantasy  ...   
4  Action|Adventure|Comedy|Family|Fantasy|Sci-Fi  ...   

  production_companies_count genres_count  popularity  vote_count  \
0                        4.0            4  185.070892     12114.0   
1                        3.0            4    6.922458       155.0   
2                        5.0            3    7.694502       336.0   
3                        3.0            2    4.878907       138.0   
4                        3.0            3     9.46307      1050.0   

  vote_average  total_actor_starpower release_month holiday_month  tot_noms  \
0          7.2               5.334665            12             1         0   
1          6.0              10.933174            01             0         0   
2          6.4              11.013046            12             1         0   
3          4.5              13.698882            03             0         1   
4          5.8               6.475240            01             0         0   

  tot_wins  
0        0  
1        0  
2        0  
3        0  
4        0  

[5 rows x 49 columns]

# Testing models:
## Prepping the data to be tested by the QDA model

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.metrics import mean_squared_error, r2_score, roc_curve, roc_auc_score, f1_score, precision_recall_curve, average_precision_score, auc


In [4]:
# review columns
for col in movies.columns.sort_values().values:
    print(col)

actor_1_facebook_likes
actor_1_name
actor_1_score
actor_2_facebook_likes
actor_2_name
actor_2_score
actor_3_facebook_likes
actor_3_name
actor_3_score
aspect_ratio
budget
cast_total_facebook_likes
color
content_rating
country
director_facebook_likes
director_name
director_score
duration
facenumber_in_poster
genres
genres_count
gross
gross_margin
holiday_month
imdb_num_code
imdb_score
language
movie_facebook_likes
movie_imdb_link
movie_title
num_critic_for_reviews
num_user_for_reviews
num_voted_users
plot_keywords
popularity
production_companies_count
rating_numeric
release_date
release_month
revenue
success_bins
successful
title_year
tot_noms
tot_wins
total_actor_starpower
vote_average
vote_count


In [5]:
# create table for model purposes
# Note that I haven't included any predictors that won't be known before a movie release
movies = movies[["duration","facenumber_in_poster","rating_numeric","gross_margin", 
                   "successful","director_score","production_companies_count","total_actor_starpower","release_month",
                   "holiday_month","tot_wins","tot_noms", "total_actor_starpower", "vote_average", "vote_count"]]
movies = movies.dropna()
movies.head(10)


duration  facenumber_in_poster  rating_numeric  gross_margin  successful  \
0     178.0                   0.0               3      0.688365           1   
1     106.0                   0.0               4     -3.037175           0   
2     150.0                   0.0               3     -1.359958           0   
3      98.0                   0.0               2      0.181842           1   
4      94.0                   3.0               2      0.239011           1   
5     146.0                   4.0               4     -0.048999           0   
6      90.0                   0.0               3     -0.325528           0   
7     121.0                   0.0               4     -0.241362           0   
8     101.0                   1.0               4     -2.179885           0   
9     110.0                   1.0               4      0.357153           1   

   director_score  production_companies_count  total_actor_starpower  \
0        3.091853                         4.0               5.334665   
1        1.766773                         3.0              10.933174   
2        1.325080                         5.0              11.013046   
3        2.650160                         3.0              13.698882   
4        1.325080                         3.0               6.475240   
5        0.441693                         4.0               3.409212   
6        2.650160                         1.0               2.816560   
7        2.208466                         1.0               6.499734   
8        0.883387                         8.0               3.409212   
9        0.883387                         4.0               3.409212   

  release_month  holiday_month  tot_wins  tot_noms  total_actor_starpower  \
0            12              1         0         0               5.334665   
1            01              0         0         0              10.933174   
2            12              1         0         0              11.013046   
3            03              0         0         1              13.698882   
4            01              0         0         0               6.475240   
5            05              0         1         2               3.409212   
6            09              0         0         0               2.816560   
7            11              1         0         0               6.499734   
8            08              0         0         0               3.409212   
9            08              0         0         0               3.409212   

   vote_average  vote_count  
0           7.2     12114.0  
1           6.0       155.0  
2           6.4       336.0  
3           4.5       138.0  
4           5.8      1050.0  
5           5.5       434.0  
6           4.9       134.0  
7           5.5       488.0  
8           3.2       106.0  
9           6.5      1950.0

In [6]:
movies["successful"].value_counts()

1    1950
0    1687
Name: successful, dtype: int64

# Set features (X) and y, create model, make train and testing data

In [7]:
# Assign X (data) and y (target)
# Change X if you want to test other parameters; this set of 9 is the final set our group decided to test
X = movies[['duration','rating_numeric', 'director_score','production_companies_count','release_month',
            "holiday_month","tot_wins","tot_noms", "total_actor_starpower"]]


y = movies["successful"].values.reshape(-1, 1)
print(X.shape, y.shape)



(3637, 10) (3637, 1)


In [8]:
# split the training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1158, train_size=0.80, stratify=y)

# Create a StandardScater model and fit it to the training data
X_scaler = StandardScaler().fit(X_train)

/Applications/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/Applications/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64, object were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


In [9]:
pd.DataFrame(y_test)[0].value_counts()

1    390
0    338
Name: 0, dtype: int64

In [10]:
# transform the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64, object were all converted to float64 by StandardScaler.
  
/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64, object were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


# Trying the PCA analysis with QDA model

In [11]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn import decomposition
from sklearn import datasets
from sklearn.svm import SVC

In [12]:
# define model; CHANGE FOR YOUR MODEL
# for SVC:
# modelSVC = SVC(C=5, gamma=0.1, kernel='linear')

model = QuadraticDiscriminantAnalysis()


In [13]:
# Function to test PCA with a range of component values

for n in range(2,10):
    
    pca = decomposition.PCA(n_components = n)
    pca.fit(X_train_scaled, y_train)
    X_train_pca = pca.transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)
    
    model.fit(X_train_pca, y_train)
    print("n="+str(n),model.score(X_test_pca, y_test),"")

n=2 0.5357142857142857 
n=3 0.5357142857142857 
n=4 0.5343406593406593 
n=5 0.5370879120879121 
n=6 0.5494505494505495 
n=7 0.5604395604395604 
n=8 0.5741758241758241 
n=9 0.5728021978021978 


/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please chan

In [14]:
pca.explained_variance_

array([3.0153534 , 1.62260995, 1.23705272, 1.03413175, 0.9635209 ,
       0.89317957, 0.69950105, 0.3593831 , 0.17870636])

In [15]:
X_train_scaled

array([[-0.04891249,  0.86840406,  0.59554403, ...,  0.46143871,
         0.32595804,  0.32595804],
       [ 0.39352046,  0.86840406, -0.60204865, ..., -0.44615102,
         0.12671206,  0.12671206],
       [-0.49134544, -0.24005904, -0.84156719, ..., -0.44615102,
        -0.80268005, -0.80268005],
       ...,
       [ 0.34927716,  0.86840406, -0.12301158, ..., -0.44615102,
         0.82302606,  0.82302606],
       [-0.75680521,  0.86840406, -0.12301158, ...,  0.00764385,
        -0.59627092, -0.59627092],
       [-0.57983203,  0.86840406, -0.84156719, ..., -0.44615102,
         1.02943519,  1.02943519]])

In [16]:
import numpy as np

In [17]:
i =np.identity(len(X_train_scaled[0]))
i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
pd.DataFrame(pca.transform(i))

0         1         2         3         4         5         6  \
0  0.218992  0.194936 -0.421923  0.339982 -0.065898 -0.319543  0.715845   
1  0.046499 -0.117803 -0.401573  0.055960 -0.768187  0.461452 -0.106641   
2  0.226688  0.063863 -0.465292  0.065181  0.005278 -0.559563 -0.640244   
3  0.076924 -0.095668 -0.270355  0.589932  0.530840  0.504027 -0.163025   
4  0.177026  0.643129  0.041081 -0.069072 -0.031541  0.220658 -0.111228   
5  0.179502  0.648568  0.048052 -0.104425  0.044785  0.155589 -0.044969   
6  0.420410 -0.087937  0.417578  0.314276 -0.196291 -0.090412 -0.082384   
7  0.430791 -0.089627  0.398561  0.326612 -0.165990 -0.045441 -0.045140   
8  0.483058 -0.205999 -0.130217 -0.392360  0.165294  0.131650  0.090790   
9  0.483058 -0.205999 -0.130217 -0.392360  0.165294  0.131650  0.090790   

          7         8  
0  0.034471  0.019080  
1 -0.071718 -0.001846  
2 -0.005962 -0.026496  
3 -0.020167  0.031631  
4  0.696482  0.038015  
5 -0.710389 -0.032206  
6 -0.050584  0.697375  
7  0.020752 -0.713284  
8  0.015771  0.013068  
9  0.015771  0.013068

In [19]:
# These column names are equivalent to rows 0-9 in pca.transform above
movies.columns

Index(['duration', 'facenumber_in_poster', 'rating_numeric', 'gross_margin',
       'successful', 'director_score', 'production_companies_count',
       'total_actor_starpower', 'release_month', 'holiday_month', 'tot_wins',
       'tot_noms', 'total_actor_starpower', 'vote_average', 'vote_count'],
      dtype='object')